spring.application.name=mastercontrol
spring.datasource.url= jdbc:postgresql://localhost:5432/aethersky
spring.datasource.username= admin
spring.datasource.password= randompassword1!
spring.datasource..driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
