spring.application.name=mastercontrol
server.port=8081

#PostgreSQL config
spring.datasource.url= jdbc:postgresql://aetherskyDB:5432/aethersky
spring.datasource.username= admin
spring.datasource.password= randompassword1!
spring.datasource..driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled = true

#Redis config
spring.data.redis.host=aetherRedis
spring.data.redis.port=6379
